/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.mx_platform_api;

import com.mx.client.ApiCallback;
import com.mx.client.ApiClient;
import com.mx.client.ApiException;
import com.mx.client.ApiResponse;
import com.mx.client.Configuration;
import com.mx.client.Pair;
import com.mx.client.ProgressRequestBody;
import com.mx.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mx.client.model.MonthlyCashFlowProfileRequestBody;
import com.mx.client.model.MonthlyCashFlowResponseBody;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MonthlyCashFlowProfileApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MonthlyCashFlowProfileApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MonthlyCashFlowProfileApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for readMonthlyCashFlowProfile
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call readMonthlyCashFlowProfileCall(String userGuid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/users/{user_guid}/monthly_cash_flow_profile"
            .replace("{" + "user_guid" + "}", localVarApiClient.escapeString(userGuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call readMonthlyCashFlowProfileValidateBeforeCall(String userGuid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userGuid' is set
        if (userGuid == null) {
            throw new ApiException("Missing the required parameter 'userGuid' when calling readMonthlyCashFlowProfile(Async)");
        }

        return readMonthlyCashFlowProfileCall(userGuid, _callback);

    }

    /**
     * Read monthly cash flow profile
     * Read monthly cash flow profile.
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @return MonthlyCashFlowResponseBody
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public MonthlyCashFlowResponseBody readMonthlyCashFlowProfile(String userGuid) throws ApiException {
        ApiResponse<MonthlyCashFlowResponseBody> localVarResp = readMonthlyCashFlowProfileWithHttpInfo(userGuid);
        return localVarResp.getData();
    }

    /**
     * Read monthly cash flow profile
     * Read monthly cash flow profile.
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @return ApiResponse&lt;MonthlyCashFlowResponseBody&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MonthlyCashFlowResponseBody> readMonthlyCashFlowProfileWithHttpInfo(String userGuid) throws ApiException {
        okhttp3.Call localVarCall = readMonthlyCashFlowProfileValidateBeforeCall(userGuid, null);
        Type localVarReturnType = new TypeToken<MonthlyCashFlowResponseBody>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Read monthly cash flow profile (asynchronously)
     * Read monthly cash flow profile.
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call readMonthlyCashFlowProfileAsync(String userGuid, final ApiCallback<MonthlyCashFlowResponseBody> _callback) throws ApiException {

        okhttp3.Call localVarCall = readMonthlyCashFlowProfileValidateBeforeCall(userGuid, _callback);
        Type localVarReturnType = new TypeToken<MonthlyCashFlowResponseBody>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateMonthlyCashFlowProfile
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @param monthlyCashFlowProfileRequestBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateMonthlyCashFlowProfileCall(String userGuid, MonthlyCashFlowProfileRequestBody monthlyCashFlowProfileRequestBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = monthlyCashFlowProfileRequestBody;

        // create path and map variables
        String localVarPath = "/users/{user_guid}/monthly_cash_flow_profile"
            .replace("{" + "user_guid" + "}", localVarApiClient.escapeString(userGuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateMonthlyCashFlowProfileValidateBeforeCall(String userGuid, MonthlyCashFlowProfileRequestBody monthlyCashFlowProfileRequestBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userGuid' is set
        if (userGuid == null) {
            throw new ApiException("Missing the required parameter 'userGuid' when calling updateMonthlyCashFlowProfile(Async)");
        }

        // verify the required parameter 'monthlyCashFlowProfileRequestBody' is set
        if (monthlyCashFlowProfileRequestBody == null) {
            throw new ApiException("Missing the required parameter 'monthlyCashFlowProfileRequestBody' when calling updateMonthlyCashFlowProfile(Async)");
        }

        return updateMonthlyCashFlowProfileCall(userGuid, monthlyCashFlowProfileRequestBody, _callback);

    }

    /**
     * Update monthly cash flow profile
     * Use this endpoint to update the attributes of a &#x60;monthly_cash_flow_profile&#x60;.
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @param monthlyCashFlowProfileRequestBody  (required)
     * @return MonthlyCashFlowResponseBody
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public MonthlyCashFlowResponseBody updateMonthlyCashFlowProfile(String userGuid, MonthlyCashFlowProfileRequestBody monthlyCashFlowProfileRequestBody) throws ApiException {
        ApiResponse<MonthlyCashFlowResponseBody> localVarResp = updateMonthlyCashFlowProfileWithHttpInfo(userGuid, monthlyCashFlowProfileRequestBody);
        return localVarResp.getData();
    }

    /**
     * Update monthly cash flow profile
     * Use this endpoint to update the attributes of a &#x60;monthly_cash_flow_profile&#x60;.
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @param monthlyCashFlowProfileRequestBody  (required)
     * @return ApiResponse&lt;MonthlyCashFlowResponseBody&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MonthlyCashFlowResponseBody> updateMonthlyCashFlowProfileWithHttpInfo(String userGuid, MonthlyCashFlowProfileRequestBody monthlyCashFlowProfileRequestBody) throws ApiException {
        okhttp3.Call localVarCall = updateMonthlyCashFlowProfileValidateBeforeCall(userGuid, monthlyCashFlowProfileRequestBody, null);
        Type localVarReturnType = new TypeToken<MonthlyCashFlowResponseBody>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update monthly cash flow profile (asynchronously)
     * Use this endpoint to update the attributes of a &#x60;monthly_cash_flow_profile&#x60;.
     * @param userGuid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;. (required)
     * @param monthlyCashFlowProfileRequestBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateMonthlyCashFlowProfileAsync(String userGuid, MonthlyCashFlowProfileRequestBody monthlyCashFlowProfileRequestBody, final ApiCallback<MonthlyCashFlowResponseBody> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateMonthlyCashFlowProfileValidateBeforeCall(userGuid, monthlyCashFlowProfileRequestBody, _callback);
        Type localVarReturnType = new TypeToken<MonthlyCashFlowResponseBody>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
