/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnhanceTransactionResponse
 */
public class EnhanceTransactionResponseTest {
    private final EnhanceTransactionResponse model = new EnhanceTransactionResponse();

    /**
     * Model tests for EnhanceTransactionResponse
     */
    @Test
    public void testEnhanceTransactionResponse() {
        // TODO: test EnhanceTransactionResponse
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isBillPay'
     */
    @Test
    public void isBillPayTest() {
        // TODO: test isBillPay
    }

    /**
     * Test the property 'isDirectDeposit'
     */
    @Test
    public void isDirectDepositTest() {
        // TODO: test isDirectDeposit
    }

    /**
     * Test the property 'isExpense'
     */
    @Test
    public void isExpenseTest() {
        // TODO: test isExpense
    }

    /**
     * Test the property 'isFee'
     */
    @Test
    public void isFeeTest() {
        // TODO: test isFee
    }

    /**
     * Test the property 'isIncome'
     */
    @Test
    public void isIncomeTest() {
        // TODO: test isIncome
    }

    /**
     * Test the property 'isInternational'
     */
    @Test
    public void isInternationalTest() {
        // TODO: test isInternational
    }

    /**
     * Test the property 'isOverdraftFee'
     */
    @Test
    public void isOverdraftFeeTest() {
        // TODO: test isOverdraftFee
    }

    /**
     * Test the property 'isPayrollAdvance'
     */
    @Test
    public void isPayrollAdvanceTest() {
        // TODO: test isPayrollAdvance
    }

    /**
     * Test the property 'merchantCategoryCode'
     */
    @Test
    public void merchantCategoryCodeTest() {
        // TODO: test merchantCategoryCode
    }

    /**
     * Test the property 'merchantGuid'
     */
    @Test
    public void merchantGuidTest() {
        // TODO: test merchantGuid
    }

    /**
     * Test the property 'originalDescription'
     */
    @Test
    public void originalDescriptionTest() {
        // TODO: test originalDescription
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
