/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentAccountBodyPaymentAccount
 */
public class PaymentAccountBodyPaymentAccountTest {
    private final PaymentAccountBodyPaymentAccount model = new PaymentAccountBodyPaymentAccount();

    /**
     * Model tests for PaymentAccountBodyPaymentAccount
     */
    @Test
    public void testPaymentAccountBodyPaymentAccount() {
        // TODO: test PaymentAccountBodyPaymentAccount
    }

    /**
     * Test the property 'accountGuid'
     */
    @Test
    public void accountGuidTest() {
        // TODO: test accountGuid
    }

    /**
     * Test the property 'memberGuid'
     */
    @Test
    public void memberGuidTest() {
        // TODO: test memberGuid
    }

    /**
     * Test the property 'userGuid'
     */
    @Test
    public void userGuidTest() {
        // TODO: test userGuid
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'routingNumber'
     */
    @Test
    public void routingNumberTest() {
        // TODO: test routingNumber
    }

    /**
     * Test the property 'transitNumber'
     */
    @Test
    public void transitNumberTest() {
        // TODO: test transitNumber
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
