/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SpendingPlanAccountResponse
 */
public class SpendingPlanAccountResponseTest {
    private final SpendingPlanAccountResponse model = new SpendingPlanAccountResponse();

    /**
     * Model tests for SpendingPlanAccountResponse
     */
    @Test
    public void testSpendingPlanAccountResponse() {
        // TODO: test SpendingPlanAccountResponse
    }

    /**
     * Test the property 'accountGuid'
     */
    @Test
    public void accountGuidTest() {
        // TODO: test accountGuid
    }

    /**
     * Test the property 'clientGuid'
     */
    @Test
    public void clientGuidTest() {
        // TODO: test clientGuid
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'spendingPlanGuid'
     */
    @Test
    public void spendingPlanGuidTest() {
        // TODO: test spendingPlanGuid
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'userGuid'
     */
    @Test
    public void userGuidTest() {
        // TODO: test userGuid
    }

}
