/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionRuleUpdateRequest
 */
public class TransactionRuleUpdateRequestTest {
    private final TransactionRuleUpdateRequest model = new TransactionRuleUpdateRequest();

    /**
     * Model tests for TransactionRuleUpdateRequest
     */
    @Test
    public void testTransactionRuleUpdateRequest() {
        // TODO: test TransactionRuleUpdateRequest
    }

    /**
     * Test the property 'categoryGuid'
     */
    @Test
    public void categoryGuidTest() {
        // TODO: test categoryGuid
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'matchDescription'
     */
    @Test
    public void matchDescriptionTest() {
        // TODO: test matchDescription
    }

}
