---
apiPackage: com.mx.client.mx-platform-api
artifactDescription: A Java library for the MX Platform API
artifactId: mx-platform-java
artifactUrl: https://github.com/mxenabled/mx-platform-java
artifactVersion: 0.8.1
developerEmail: devexperience@mx.com
developerName: MX
developerOrganization: MX Technologies Inc.
developerOrganizationUrl: https://www.mx.com/
groupId: com.mx
hideGenerationTimestamp: true
invokerPackage: com.mx.client
licenseName: MIT
licenseUrl: https://github.com/mxenabled/mx-platform-java/LICENSE
modelPackage: com.mx.client.model
scmConnection: https://github.com/mxenabled/mx-platform-java.git
scmDeveloperConnection: git@github.com:mxenabled/mx-platform-java.git
scmUrl: https://github.com/mxenabled/mx-platform-java
