/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mx.client.model.AuthorizationCodeResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AuthorizationCodeResponseBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuthorizationCodeResponseBody {
  public static final String SERIALIZED_NAME_AUTHORIZATION_CODE = "authorization_code";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION_CODE)
  private List<AuthorizationCodeResponse> authorizationCode = null;

  public AuthorizationCodeResponseBody() { 
  }

  public AuthorizationCodeResponseBody authorizationCode(List<AuthorizationCodeResponse> authorizationCode) {
    
    this.authorizationCode = authorizationCode;
    return this;
  }

  public AuthorizationCodeResponseBody addAuthorizationCodeItem(AuthorizationCodeResponse authorizationCodeItem) {
    if (this.authorizationCode == null) {
      this.authorizationCode = new ArrayList<AuthorizationCodeResponse>();
    }
    this.authorizationCode.add(authorizationCodeItem);
    return this;
  }

   /**
   * Get authorizationCode
   * @return authorizationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AuthorizationCodeResponse> getAuthorizationCode() {
    return authorizationCode;
  }


  public void setAuthorizationCode(List<AuthorizationCodeResponse> authorizationCode) {
    this.authorizationCode = authorizationCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationCodeResponseBody authorizationCodeResponseBody = (AuthorizationCodeResponseBody) o;
    return Objects.equals(this.authorizationCode, authorizationCodeResponseBody.authorizationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationCodeResponseBody {\n");
    sb.append("    authorizationCode: ").append(toIndentedString(authorizationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

