/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mx.client.JSON;

/**
 * InvestmentHoldingResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class InvestmentHoldingResponse {
  public static final String SERIALIZED_NAME_ACCOUNT_GUID = "account_guid";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_GUID)
  private String accountGuid;

  public static final String SERIALIZED_NAME_COST_BASIS = "cost_basis";
  @SerializedName(SERIALIZED_NAME_COST_BASIS)
  private BigDecimal costBasis;

  public static final String SERIALIZED_NAME_COUPON_YIELD = "coupon_yield";
  @SerializedName(SERIALIZED_NAME_COUPON_YIELD)
  private String couponYield;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currency_code";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_CURRENT_PRICE = "current_price";
  @SerializedName(SERIALIZED_NAME_CURRENT_PRICE)
  private BigDecimal currentPrice;

  public static final String SERIALIZED_NAME_DAILY_CHANGE = "daily_change";
  @SerializedName(SERIALIZED_NAME_DAILY_CHANGE)
  private BigDecimal dailyChange;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  private String expiration;

  public static final String SERIALIZED_NAME_FACE_VALUE = "face_value";
  @SerializedName(SERIALIZED_NAME_FACE_VALUE)
  private BigDecimal faceValue;

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private String frequency;

  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  private String guid;

  public static final String SERIALIZED_NAME_MARKET_VALUE = "market_value";
  @SerializedName(SERIALIZED_NAME_MARKET_VALUE)
  private BigDecimal marketValue;

  public static final String SERIALIZED_NAME_MATURITY_DATE = "maturity_date";
  @SerializedName(SERIALIZED_NAME_MATURITY_DATE)
  private String maturityDate;

  public static final String SERIALIZED_NAME_PERCENTAGE_CHANGE = "percentage_change";
  @SerializedName(SERIALIZED_NAME_PERCENTAGE_CHANGE)
  private BigDecimal percentageChange;

  public static final String SERIALIZED_NAME_PURCHASE_PRICE = "purchase_price";
  @SerializedName(SERIALIZED_NAME_PURCHASE_PRICE)
  private BigDecimal purchasePrice;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private String quantity;

  public static final String SERIALIZED_NAME_RATE = "rate";
  @SerializedName(SERIALIZED_NAME_RATE)
  private BigDecimal rate;

  public static final String SERIALIZED_NAME_STRIKE_PRICE = "strike_price";
  @SerializedName(SERIALIZED_NAME_STRIKE_PRICE)
  private BigDecimal strikePrice;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  private String symbol;

  public static final String SERIALIZED_NAME_TERM = "term";
  @SerializedName(SERIALIZED_NAME_TERM)
  private String term;

  public static final String SERIALIZED_NAME_TODAY_UGL_AMOUNT = "today_ugl_amount";
  @SerializedName(SERIALIZED_NAME_TODAY_UGL_AMOUNT)
  private BigDecimal todayUglAmount;

  public static final String SERIALIZED_NAME_TODAY_UGL_PERCENTAGE = "today_ugl_percentage";
  @SerializedName(SERIALIZED_NAME_TODAY_UGL_PERCENTAGE)
  private BigDecimal todayUglPercentage;

  public static final String SERIALIZED_NAME_TOTAL_UGL_AMOUNT = "total_ugl_amount";
  @SerializedName(SERIALIZED_NAME_TOTAL_UGL_AMOUNT)
  private BigDecimal totalUglAmount;

  public static final String SERIALIZED_NAME_TOTAL_UGL_PERCENTAGE = "total_ugl_percentage";
  @SerializedName(SERIALIZED_NAME_TOTAL_UGL_PERCENTAGE)
  private BigDecimal totalUglPercentage;

  public static final String SERIALIZED_NAME_UNVESTED_QUANTITY = "unvested_quantity";
  @SerializedName(SERIALIZED_NAME_UNVESTED_QUANTITY)
  private BigDecimal unvestedQuantity;

  public static final String SERIALIZED_NAME_UNVESTED_VALUE = "unvested_value";
  @SerializedName(SERIALIZED_NAME_UNVESTED_VALUE)
  private BigDecimal unvestedValue;

  public static final String SERIALIZED_NAME_USER_GUID = "user_guid";
  @SerializedName(SERIALIZED_NAME_USER_GUID)
  private String userGuid;

  public static final String SERIALIZED_NAME_VESTED_QUANTITY = "vested_quantity";
  @SerializedName(SERIALIZED_NAME_VESTED_QUANTITY)
  private BigDecimal vestedQuantity;

  public static final String SERIALIZED_NAME_VESTED_VALUE = "vested_value";
  @SerializedName(SERIALIZED_NAME_VESTED_VALUE)
  private BigDecimal vestedValue;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_CURRENT_PRICE_AS_OF = "current_price_as_of";
  @SerializedName(SERIALIZED_NAME_CURRENT_PRICE_AS_OF)
  private String currentPriceAsOf;

  public static final String SERIALIZED_NAME_ISSUE_DATE = "issue_date";
  @SerializedName(SERIALIZED_NAME_ISSUE_DATE)
  private String issueDate;

  public static final String SERIALIZED_NAME_VESTING_START_DATE = "vesting_start_date";
  @SerializedName(SERIALIZED_NAME_VESTING_START_DATE)
  private String vestingStartDate;

  public static final String SERIALIZED_NAME_VESTING_END_DATE = "vesting_end_date";
  @SerializedName(SERIALIZED_NAME_VESTING_END_DATE)
  private String vestingEndDate;

  public static final String SERIALIZED_NAME_PUT_OR_CALL = "put_or_call";
  @SerializedName(SERIALIZED_NAME_PUT_OR_CALL)
  private String putOrCall;

  public static final String SERIALIZED_NAME_HOLDING_TYPE = "holding_type";
  @SerializedName(SERIALIZED_NAME_HOLDING_TYPE)
  private String holdingType;

  public static final String SERIALIZED_NAME_TERM_UNIT = "term_unit";
  @SerializedName(SERIALIZED_NAME_TERM_UNIT)
  private String termUnit;

  public InvestmentHoldingResponse() {
  }

  public InvestmentHoldingResponse accountGuid(String accountGuid) {
    
    this.accountGuid = accountGuid;
    return this;
  }

   /**
   * Get accountGuid
   * @return accountGuid
  **/
  @javax.annotation.Nullable
  public String getAccountGuid() {
    return accountGuid;
  }


  public void setAccountGuid(String accountGuid) {
    this.accountGuid = accountGuid;
  }


  public InvestmentHoldingResponse costBasis(BigDecimal costBasis) {
    
    this.costBasis = costBasis;
    return this;
  }

   /**
   * Get costBasis
   * @return costBasis
  **/
  @javax.annotation.Nullable
  public BigDecimal getCostBasis() {
    return costBasis;
  }


  public void setCostBasis(BigDecimal costBasis) {
    this.costBasis = costBasis;
  }


  public InvestmentHoldingResponse couponYield(String couponYield) {
    
    this.couponYield = couponYield;
    return this;
  }

   /**
   * Get couponYield
   * @return couponYield
  **/
  @javax.annotation.Nullable
  public String getCouponYield() {
    return couponYield;
  }


  public void setCouponYield(String couponYield) {
    this.couponYield = couponYield;
  }


  public InvestmentHoldingResponse currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public InvestmentHoldingResponse currentPrice(BigDecimal currentPrice) {
    
    this.currentPrice = currentPrice;
    return this;
  }

   /**
   * Get currentPrice
   * @return currentPrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getCurrentPrice() {
    return currentPrice;
  }


  public void setCurrentPrice(BigDecimal currentPrice) {
    this.currentPrice = currentPrice;
  }


  public InvestmentHoldingResponse dailyChange(BigDecimal dailyChange) {
    
    this.dailyChange = dailyChange;
    return this;
  }

   /**
   * Get dailyChange
   * @return dailyChange
  **/
  @javax.annotation.Nullable
  public BigDecimal getDailyChange() {
    return dailyChange;
  }


  public void setDailyChange(BigDecimal dailyChange) {
    this.dailyChange = dailyChange;
  }


  public InvestmentHoldingResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public InvestmentHoldingResponse expiration(String expiration) {
    
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @javax.annotation.Nullable
  public String getExpiration() {
    return expiration;
  }


  public void setExpiration(String expiration) {
    this.expiration = expiration;
  }


  public InvestmentHoldingResponse faceValue(BigDecimal faceValue) {
    
    this.faceValue = faceValue;
    return this;
  }

   /**
   * Get faceValue
   * @return faceValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getFaceValue() {
    return faceValue;
  }


  public void setFaceValue(BigDecimal faceValue) {
    this.faceValue = faceValue;
  }


  public InvestmentHoldingResponse frequency(String frequency) {
    
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @javax.annotation.Nullable
  public String getFrequency() {
    return frequency;
  }


  public void setFrequency(String frequency) {
    this.frequency = frequency;
  }


  public InvestmentHoldingResponse guid(String guid) {
    
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @javax.annotation.Nullable
  public String getGuid() {
    return guid;
  }


  public void setGuid(String guid) {
    this.guid = guid;
  }


  public InvestmentHoldingResponse marketValue(BigDecimal marketValue) {
    
    this.marketValue = marketValue;
    return this;
  }

   /**
   * Get marketValue
   * @return marketValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getMarketValue() {
    return marketValue;
  }


  public void setMarketValue(BigDecimal marketValue) {
    this.marketValue = marketValue;
  }


  public InvestmentHoldingResponse maturityDate(String maturityDate) {
    
    this.maturityDate = maturityDate;
    return this;
  }

   /**
   * Get maturityDate
   * @return maturityDate
  **/
  @javax.annotation.Nullable
  public String getMaturityDate() {
    return maturityDate;
  }


  public void setMaturityDate(String maturityDate) {
    this.maturityDate = maturityDate;
  }


  public InvestmentHoldingResponse percentageChange(BigDecimal percentageChange) {
    
    this.percentageChange = percentageChange;
    return this;
  }

   /**
   * Get percentageChange
   * @return percentageChange
  **/
  @javax.annotation.Nullable
  public BigDecimal getPercentageChange() {
    return percentageChange;
  }


  public void setPercentageChange(BigDecimal percentageChange) {
    this.percentageChange = percentageChange;
  }


  public InvestmentHoldingResponse purchasePrice(BigDecimal purchasePrice) {
    
    this.purchasePrice = purchasePrice;
    return this;
  }

   /**
   * Get purchasePrice
   * @return purchasePrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getPurchasePrice() {
    return purchasePrice;
  }


  public void setPurchasePrice(BigDecimal purchasePrice) {
    this.purchasePrice = purchasePrice;
  }


  public InvestmentHoldingResponse quantity(String quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  public String getQuantity() {
    return quantity;
  }


  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  public InvestmentHoldingResponse rate(BigDecimal rate) {
    
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @javax.annotation.Nullable
  public BigDecimal getRate() {
    return rate;
  }


  public void setRate(BigDecimal rate) {
    this.rate = rate;
  }


  public InvestmentHoldingResponse strikePrice(BigDecimal strikePrice) {
    
    this.strikePrice = strikePrice;
    return this;
  }

   /**
   * Get strikePrice
   * @return strikePrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getStrikePrice() {
    return strikePrice;
  }


  public void setStrikePrice(BigDecimal strikePrice) {
    this.strikePrice = strikePrice;
  }


  public InvestmentHoldingResponse symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @javax.annotation.Nullable
  public String getSymbol() {
    return symbol;
  }


  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public InvestmentHoldingResponse term(String term) {
    
    this.term = term;
    return this;
  }

   /**
   * Get term
   * @return term
  **/
  @javax.annotation.Nullable
  public String getTerm() {
    return term;
  }


  public void setTerm(String term) {
    this.term = term;
  }


  public InvestmentHoldingResponse todayUglAmount(BigDecimal todayUglAmount) {
    
    this.todayUglAmount = todayUglAmount;
    return this;
  }

   /**
   * Get todayUglAmount
   * @return todayUglAmount
  **/
  @javax.annotation.Nullable
  public BigDecimal getTodayUglAmount() {
    return todayUglAmount;
  }


  public void setTodayUglAmount(BigDecimal todayUglAmount) {
    this.todayUglAmount = todayUglAmount;
  }


  public InvestmentHoldingResponse todayUglPercentage(BigDecimal todayUglPercentage) {
    
    this.todayUglPercentage = todayUglPercentage;
    return this;
  }

   /**
   * Get todayUglPercentage
   * @return todayUglPercentage
  **/
  @javax.annotation.Nullable
  public BigDecimal getTodayUglPercentage() {
    return todayUglPercentage;
  }


  public void setTodayUglPercentage(BigDecimal todayUglPercentage) {
    this.todayUglPercentage = todayUglPercentage;
  }


  public InvestmentHoldingResponse totalUglAmount(BigDecimal totalUglAmount) {
    
    this.totalUglAmount = totalUglAmount;
    return this;
  }

   /**
   * Get totalUglAmount
   * @return totalUglAmount
  **/
  @javax.annotation.Nullable
  public BigDecimal getTotalUglAmount() {
    return totalUglAmount;
  }


  public void setTotalUglAmount(BigDecimal totalUglAmount) {
    this.totalUglAmount = totalUglAmount;
  }


  public InvestmentHoldingResponse totalUglPercentage(BigDecimal totalUglPercentage) {
    
    this.totalUglPercentage = totalUglPercentage;
    return this;
  }

   /**
   * Get totalUglPercentage
   * @return totalUglPercentage
  **/
  @javax.annotation.Nullable
  public BigDecimal getTotalUglPercentage() {
    return totalUglPercentage;
  }


  public void setTotalUglPercentage(BigDecimal totalUglPercentage) {
    this.totalUglPercentage = totalUglPercentage;
  }


  public InvestmentHoldingResponse unvestedQuantity(BigDecimal unvestedQuantity) {
    
    this.unvestedQuantity = unvestedQuantity;
    return this;
  }

   /**
   * Get unvestedQuantity
   * @return unvestedQuantity
  **/
  @javax.annotation.Nullable
  public BigDecimal getUnvestedQuantity() {
    return unvestedQuantity;
  }


  public void setUnvestedQuantity(BigDecimal unvestedQuantity) {
    this.unvestedQuantity = unvestedQuantity;
  }


  public InvestmentHoldingResponse unvestedValue(BigDecimal unvestedValue) {
    
    this.unvestedValue = unvestedValue;
    return this;
  }

   /**
   * Get unvestedValue
   * @return unvestedValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getUnvestedValue() {
    return unvestedValue;
  }


  public void setUnvestedValue(BigDecimal unvestedValue) {
    this.unvestedValue = unvestedValue;
  }


  public InvestmentHoldingResponse userGuid(String userGuid) {
    
    this.userGuid = userGuid;
    return this;
  }

   /**
   * Get userGuid
   * @return userGuid
  **/
  @javax.annotation.Nullable
  public String getUserGuid() {
    return userGuid;
  }


  public void setUserGuid(String userGuid) {
    this.userGuid = userGuid;
  }


  public InvestmentHoldingResponse vestedQuantity(BigDecimal vestedQuantity) {
    
    this.vestedQuantity = vestedQuantity;
    return this;
  }

   /**
   * Get vestedQuantity
   * @return vestedQuantity
  **/
  @javax.annotation.Nullable
  public BigDecimal getVestedQuantity() {
    return vestedQuantity;
  }


  public void setVestedQuantity(BigDecimal vestedQuantity) {
    this.vestedQuantity = vestedQuantity;
  }


  public InvestmentHoldingResponse vestedValue(BigDecimal vestedValue) {
    
    this.vestedValue = vestedValue;
    return this;
  }

   /**
   * Get vestedValue
   * @return vestedValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getVestedValue() {
    return vestedValue;
  }


  public void setVestedValue(BigDecimal vestedValue) {
    this.vestedValue = vestedValue;
  }


  public InvestmentHoldingResponse createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public InvestmentHoldingResponse currentPriceAsOf(String currentPriceAsOf) {
    
    this.currentPriceAsOf = currentPriceAsOf;
    return this;
  }

   /**
   * Get currentPriceAsOf
   * @return currentPriceAsOf
  **/
  @javax.annotation.Nullable
  public String getCurrentPriceAsOf() {
    return currentPriceAsOf;
  }


  public void setCurrentPriceAsOf(String currentPriceAsOf) {
    this.currentPriceAsOf = currentPriceAsOf;
  }


  public InvestmentHoldingResponse issueDate(String issueDate) {
    
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/
  @javax.annotation.Nullable
  public String getIssueDate() {
    return issueDate;
  }


  public void setIssueDate(String issueDate) {
    this.issueDate = issueDate;
  }


  public InvestmentHoldingResponse vestingStartDate(String vestingStartDate) {
    
    this.vestingStartDate = vestingStartDate;
    return this;
  }

   /**
   * Get vestingStartDate
   * @return vestingStartDate
  **/
  @javax.annotation.Nullable
  public String getVestingStartDate() {
    return vestingStartDate;
  }


  public void setVestingStartDate(String vestingStartDate) {
    this.vestingStartDate = vestingStartDate;
  }


  public InvestmentHoldingResponse vestingEndDate(String vestingEndDate) {
    
    this.vestingEndDate = vestingEndDate;
    return this;
  }

   /**
   * Get vestingEndDate
   * @return vestingEndDate
  **/
  @javax.annotation.Nullable
  public String getVestingEndDate() {
    return vestingEndDate;
  }


  public void setVestingEndDate(String vestingEndDate) {
    this.vestingEndDate = vestingEndDate;
  }


  public InvestmentHoldingResponse putOrCall(String putOrCall) {
    
    this.putOrCall = putOrCall;
    return this;
  }

   /**
   * Get putOrCall
   * @return putOrCall
  **/
  @javax.annotation.Nullable
  public String getPutOrCall() {
    return putOrCall;
  }


  public void setPutOrCall(String putOrCall) {
    this.putOrCall = putOrCall;
  }


  public InvestmentHoldingResponse holdingType(String holdingType) {
    
    this.holdingType = holdingType;
    return this;
  }

   /**
   * Get holdingType
   * @return holdingType
  **/
  @javax.annotation.Nullable
  public String getHoldingType() {
    return holdingType;
  }


  public void setHoldingType(String holdingType) {
    this.holdingType = holdingType;
  }


  public InvestmentHoldingResponse termUnit(String termUnit) {
    
    this.termUnit = termUnit;
    return this;
  }

   /**
   * Get termUnit
   * @return termUnit
  **/
  @javax.annotation.Nullable
  public String getTermUnit() {
    return termUnit;
  }


  public void setTermUnit(String termUnit) {
    this.termUnit = termUnit;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestmentHoldingResponse investmentHoldingResponse = (InvestmentHoldingResponse) o;
    return Objects.equals(this.accountGuid, investmentHoldingResponse.accountGuid) &&
        Objects.equals(this.costBasis, investmentHoldingResponse.costBasis) &&
        Objects.equals(this.couponYield, investmentHoldingResponse.couponYield) &&
        Objects.equals(this.currencyCode, investmentHoldingResponse.currencyCode) &&
        Objects.equals(this.currentPrice, investmentHoldingResponse.currentPrice) &&
        Objects.equals(this.dailyChange, investmentHoldingResponse.dailyChange) &&
        Objects.equals(this.description, investmentHoldingResponse.description) &&
        Objects.equals(this.expiration, investmentHoldingResponse.expiration) &&
        Objects.equals(this.faceValue, investmentHoldingResponse.faceValue) &&
        Objects.equals(this.frequency, investmentHoldingResponse.frequency) &&
        Objects.equals(this.guid, investmentHoldingResponse.guid) &&
        Objects.equals(this.marketValue, investmentHoldingResponse.marketValue) &&
        Objects.equals(this.maturityDate, investmentHoldingResponse.maturityDate) &&
        Objects.equals(this.percentageChange, investmentHoldingResponse.percentageChange) &&
        Objects.equals(this.purchasePrice, investmentHoldingResponse.purchasePrice) &&
        Objects.equals(this.quantity, investmentHoldingResponse.quantity) &&
        Objects.equals(this.rate, investmentHoldingResponse.rate) &&
        Objects.equals(this.strikePrice, investmentHoldingResponse.strikePrice) &&
        Objects.equals(this.symbol, investmentHoldingResponse.symbol) &&
        Objects.equals(this.term, investmentHoldingResponse.term) &&
        Objects.equals(this.todayUglAmount, investmentHoldingResponse.todayUglAmount) &&
        Objects.equals(this.todayUglPercentage, investmentHoldingResponse.todayUglPercentage) &&
        Objects.equals(this.totalUglAmount, investmentHoldingResponse.totalUglAmount) &&
        Objects.equals(this.totalUglPercentage, investmentHoldingResponse.totalUglPercentage) &&
        Objects.equals(this.unvestedQuantity, investmentHoldingResponse.unvestedQuantity) &&
        Objects.equals(this.unvestedValue, investmentHoldingResponse.unvestedValue) &&
        Objects.equals(this.userGuid, investmentHoldingResponse.userGuid) &&
        Objects.equals(this.vestedQuantity, investmentHoldingResponse.vestedQuantity) &&
        Objects.equals(this.vestedValue, investmentHoldingResponse.vestedValue) &&
        Objects.equals(this.createdAt, investmentHoldingResponse.createdAt) &&
        Objects.equals(this.currentPriceAsOf, investmentHoldingResponse.currentPriceAsOf) &&
        Objects.equals(this.issueDate, investmentHoldingResponse.issueDate) &&
        Objects.equals(this.vestingStartDate, investmentHoldingResponse.vestingStartDate) &&
        Objects.equals(this.vestingEndDate, investmentHoldingResponse.vestingEndDate) &&
        Objects.equals(this.putOrCall, investmentHoldingResponse.putOrCall) &&
        Objects.equals(this.holdingType, investmentHoldingResponse.holdingType) &&
        Objects.equals(this.termUnit, investmentHoldingResponse.termUnit);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountGuid, costBasis, couponYield, currencyCode, currentPrice, dailyChange, description, expiration, faceValue, frequency, guid, marketValue, maturityDate, percentageChange, purchasePrice, quantity, rate, strikePrice, symbol, term, todayUglAmount, todayUglPercentage, totalUglAmount, totalUglPercentage, unvestedQuantity, unvestedValue, userGuid, vestedQuantity, vestedValue, createdAt, currentPriceAsOf, issueDate, vestingStartDate, vestingEndDate, putOrCall, holdingType, termUnit);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvestmentHoldingResponse {\n");
    sb.append("    accountGuid: ").append(toIndentedString(accountGuid)).append("\n");
    sb.append("    costBasis: ").append(toIndentedString(costBasis)).append("\n");
    sb.append("    couponYield: ").append(toIndentedString(couponYield)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    currentPrice: ").append(toIndentedString(currentPrice)).append("\n");
    sb.append("    dailyChange: ").append(toIndentedString(dailyChange)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    faceValue: ").append(toIndentedString(faceValue)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    marketValue: ").append(toIndentedString(marketValue)).append("\n");
    sb.append("    maturityDate: ").append(toIndentedString(maturityDate)).append("\n");
    sb.append("    percentageChange: ").append(toIndentedString(percentageChange)).append("\n");
    sb.append("    purchasePrice: ").append(toIndentedString(purchasePrice)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    strikePrice: ").append(toIndentedString(strikePrice)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("    todayUglAmount: ").append(toIndentedString(todayUglAmount)).append("\n");
    sb.append("    todayUglPercentage: ").append(toIndentedString(todayUglPercentage)).append("\n");
    sb.append("    totalUglAmount: ").append(toIndentedString(totalUglAmount)).append("\n");
    sb.append("    totalUglPercentage: ").append(toIndentedString(totalUglPercentage)).append("\n");
    sb.append("    unvestedQuantity: ").append(toIndentedString(unvestedQuantity)).append("\n");
    sb.append("    unvestedValue: ").append(toIndentedString(unvestedValue)).append("\n");
    sb.append("    userGuid: ").append(toIndentedString(userGuid)).append("\n");
    sb.append("    vestedQuantity: ").append(toIndentedString(vestedQuantity)).append("\n");
    sb.append("    vestedValue: ").append(toIndentedString(vestedValue)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    currentPriceAsOf: ").append(toIndentedString(currentPriceAsOf)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    vestingStartDate: ").append(toIndentedString(vestingStartDate)).append("\n");
    sb.append("    vestingEndDate: ").append(toIndentedString(vestingEndDate)).append("\n");
    sb.append("    putOrCall: ").append(toIndentedString(putOrCall)).append("\n");
    sb.append("    holdingType: ").append(toIndentedString(holdingType)).append("\n");
    sb.append("    termUnit: ").append(toIndentedString(termUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("account_guid");
    openapiFields.add("cost_basis");
    openapiFields.add("coupon_yield");
    openapiFields.add("currency_code");
    openapiFields.add("current_price");
    openapiFields.add("daily_change");
    openapiFields.add("description");
    openapiFields.add("expiration");
    openapiFields.add("face_value");
    openapiFields.add("frequency");
    openapiFields.add("guid");
    openapiFields.add("market_value");
    openapiFields.add("maturity_date");
    openapiFields.add("percentage_change");
    openapiFields.add("purchase_price");
    openapiFields.add("quantity");
    openapiFields.add("rate");
    openapiFields.add("strike_price");
    openapiFields.add("symbol");
    openapiFields.add("term");
    openapiFields.add("today_ugl_amount");
    openapiFields.add("today_ugl_percentage");
    openapiFields.add("total_ugl_amount");
    openapiFields.add("total_ugl_percentage");
    openapiFields.add("unvested_quantity");
    openapiFields.add("unvested_value");
    openapiFields.add("user_guid");
    openapiFields.add("vested_quantity");
    openapiFields.add("vested_value");
    openapiFields.add("created_at");
    openapiFields.add("current_price_as_of");
    openapiFields.add("issue_date");
    openapiFields.add("vesting_start_date");
    openapiFields.add("vesting_end_date");
    openapiFields.add("put_or_call");
    openapiFields.add("holding_type");
    openapiFields.add("term_unit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to InvestmentHoldingResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InvestmentHoldingResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InvestmentHoldingResponse is not found in the empty JSON string", InvestmentHoldingResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InvestmentHoldingResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InvestmentHoldingResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("account_guid") != null && !jsonObj.get("account_guid").isJsonNull()) && !jsonObj.get("account_guid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_guid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_guid").toString()));
      }
      if ((jsonObj.get("coupon_yield") != null && !jsonObj.get("coupon_yield").isJsonNull()) && !jsonObj.get("coupon_yield").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `coupon_yield` to be a primitive type in the JSON string but got `%s`", jsonObj.get("coupon_yield").toString()));
      }
      if ((jsonObj.get("currency_code") != null && !jsonObj.get("currency_code").isJsonNull()) && !jsonObj.get("currency_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency_code").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("expiration") != null && !jsonObj.get("expiration").isJsonNull()) && !jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      if ((jsonObj.get("frequency") != null && !jsonObj.get("frequency").isJsonNull()) && !jsonObj.get("frequency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frequency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frequency").toString()));
      }
      if ((jsonObj.get("guid") != null && !jsonObj.get("guid").isJsonNull()) && !jsonObj.get("guid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `guid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("guid").toString()));
      }
      if ((jsonObj.get("maturity_date") != null && !jsonObj.get("maturity_date").isJsonNull()) && !jsonObj.get("maturity_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maturity_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maturity_date").toString()));
      }
      if ((jsonObj.get("quantity") != null && !jsonObj.get("quantity").isJsonNull()) && !jsonObj.get("quantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quantity").toString()));
      }
      if ((jsonObj.get("symbol") != null && !jsonObj.get("symbol").isJsonNull()) && !jsonObj.get("symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
      }
      if ((jsonObj.get("term") != null && !jsonObj.get("term").isJsonNull()) && !jsonObj.get("term").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `term` to be a primitive type in the JSON string but got `%s`", jsonObj.get("term").toString()));
      }
      if ((jsonObj.get("user_guid") != null && !jsonObj.get("user_guid").isJsonNull()) && !jsonObj.get("user_guid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_guid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_guid").toString()));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("current_price_as_of") != null && !jsonObj.get("current_price_as_of").isJsonNull()) && !jsonObj.get("current_price_as_of").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `current_price_as_of` to be a primitive type in the JSON string but got `%s`", jsonObj.get("current_price_as_of").toString()));
      }
      if ((jsonObj.get("issue_date") != null && !jsonObj.get("issue_date").isJsonNull()) && !jsonObj.get("issue_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issue_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issue_date").toString()));
      }
      if ((jsonObj.get("vesting_start_date") != null && !jsonObj.get("vesting_start_date").isJsonNull()) && !jsonObj.get("vesting_start_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vesting_start_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vesting_start_date").toString()));
      }
      if ((jsonObj.get("vesting_end_date") != null && !jsonObj.get("vesting_end_date").isJsonNull()) && !jsonObj.get("vesting_end_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vesting_end_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vesting_end_date").toString()));
      }
      if ((jsonObj.get("put_or_call") != null && !jsonObj.get("put_or_call").isJsonNull()) && !jsonObj.get("put_or_call").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `put_or_call` to be a primitive type in the JSON string but got `%s`", jsonObj.get("put_or_call").toString()));
      }
      if ((jsonObj.get("holding_type") != null && !jsonObj.get("holding_type").isJsonNull()) && !jsonObj.get("holding_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `holding_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("holding_type").toString()));
      }
      if ((jsonObj.get("term_unit") != null && !jsonObj.get("term_unit").isJsonNull()) && !jsonObj.get("term_unit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `term_unit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("term_unit").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InvestmentHoldingResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InvestmentHoldingResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InvestmentHoldingResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InvestmentHoldingResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<InvestmentHoldingResponse>() {
           @Override
           public void write(JsonWriter out, InvestmentHoldingResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InvestmentHoldingResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InvestmentHoldingResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InvestmentHoldingResponse
  * @throws IOException if the JSON string is invalid with respect to InvestmentHoldingResponse
  */
  public static InvestmentHoldingResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InvestmentHoldingResponse.class);
  }

 /**
  * Convert an instance of InvestmentHoldingResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

