/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mx.client.model.PaymentProcessorAuthorizationCodeRequest;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mx.client.JSON;

/**
 * PaymentProcessorAuthorizationCodeRequestBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PaymentProcessorAuthorizationCodeRequestBody {
  public static final String SERIALIZED_NAME_PAYMENT_PROCESSOR_AUTHORIZATION_CODE = "payment_processor_authorization_code";
  @SerializedName(SERIALIZED_NAME_PAYMENT_PROCESSOR_AUTHORIZATION_CODE)
  private PaymentProcessorAuthorizationCodeRequest paymentProcessorAuthorizationCode;

  public PaymentProcessorAuthorizationCodeRequestBody() {
  }

  public PaymentProcessorAuthorizationCodeRequestBody paymentProcessorAuthorizationCode(PaymentProcessorAuthorizationCodeRequest paymentProcessorAuthorizationCode) {
    
    this.paymentProcessorAuthorizationCode = paymentProcessorAuthorizationCode;
    return this;
  }

   /**
   * Get paymentProcessorAuthorizationCode
   * @return paymentProcessorAuthorizationCode
  **/
  @javax.annotation.Nullable
  public PaymentProcessorAuthorizationCodeRequest getPaymentProcessorAuthorizationCode() {
    return paymentProcessorAuthorizationCode;
  }


  public void setPaymentProcessorAuthorizationCode(PaymentProcessorAuthorizationCodeRequest paymentProcessorAuthorizationCode) {
    this.paymentProcessorAuthorizationCode = paymentProcessorAuthorizationCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentProcessorAuthorizationCodeRequestBody paymentProcessorAuthorizationCodeRequestBody = (PaymentProcessorAuthorizationCodeRequestBody) o;
    return Objects.equals(this.paymentProcessorAuthorizationCode, paymentProcessorAuthorizationCodeRequestBody.paymentProcessorAuthorizationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentProcessorAuthorizationCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentProcessorAuthorizationCodeRequestBody {\n");
    sb.append("    paymentProcessorAuthorizationCode: ").append(toIndentedString(paymentProcessorAuthorizationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payment_processor_authorization_code");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentProcessorAuthorizationCodeRequestBody
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentProcessorAuthorizationCodeRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentProcessorAuthorizationCodeRequestBody is not found in the empty JSON string", PaymentProcessorAuthorizationCodeRequestBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PaymentProcessorAuthorizationCodeRequestBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PaymentProcessorAuthorizationCodeRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `payment_processor_authorization_code`
      if (jsonObj.get("payment_processor_authorization_code") != null && !jsonObj.get("payment_processor_authorization_code").isJsonNull()) {
        PaymentProcessorAuthorizationCodeRequest.validateJsonElement(jsonObj.get("payment_processor_authorization_code"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentProcessorAuthorizationCodeRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentProcessorAuthorizationCodeRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentProcessorAuthorizationCodeRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentProcessorAuthorizationCodeRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentProcessorAuthorizationCodeRequestBody>() {
           @Override
           public void write(JsonWriter out, PaymentProcessorAuthorizationCodeRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentProcessorAuthorizationCodeRequestBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentProcessorAuthorizationCodeRequestBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentProcessorAuthorizationCodeRequestBody
  * @throws IOException if the JSON string is invalid with respect to PaymentProcessorAuthorizationCodeRequestBody
  */
  public static PaymentProcessorAuthorizationCodeRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentProcessorAuthorizationCodeRequestBody.class);
  }

 /**
  * Convert an instance of PaymentProcessorAuthorizationCodeRequestBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

