/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mx.client.model.TaxDocumentResponse;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mx.client.JSON;

/**
 * TaxDocumentResponseBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TaxDocumentResponseBody {
  public static final String SERIALIZED_NAME_TAX_DOCUMENT = "tax_document";
  @SerializedName(SERIALIZED_NAME_TAX_DOCUMENT)
  private TaxDocumentResponse taxDocument;

  public TaxDocumentResponseBody() {
  }

  public TaxDocumentResponseBody taxDocument(TaxDocumentResponse taxDocument) {
    
    this.taxDocument = taxDocument;
    return this;
  }

   /**
   * Get taxDocument
   * @return taxDocument
  **/
  @javax.annotation.Nullable
  public TaxDocumentResponse getTaxDocument() {
    return taxDocument;
  }


  public void setTaxDocument(TaxDocumentResponse taxDocument) {
    this.taxDocument = taxDocument;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxDocumentResponseBody taxDocumentResponseBody = (TaxDocumentResponseBody) o;
    return Objects.equals(this.taxDocument, taxDocumentResponseBody.taxDocument);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxDocument);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxDocumentResponseBody {\n");
    sb.append("    taxDocument: ").append(toIndentedString(taxDocument)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tax_document");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TaxDocumentResponseBody
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TaxDocumentResponseBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TaxDocumentResponseBody is not found in the empty JSON string", TaxDocumentResponseBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TaxDocumentResponseBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TaxDocumentResponseBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `tax_document`
      if (jsonObj.get("tax_document") != null && !jsonObj.get("tax_document").isJsonNull()) {
        TaxDocumentResponse.validateJsonElement(jsonObj.get("tax_document"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TaxDocumentResponseBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TaxDocumentResponseBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TaxDocumentResponseBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TaxDocumentResponseBody.class));

       return (TypeAdapter<T>) new TypeAdapter<TaxDocumentResponseBody>() {
           @Override
           public void write(JsonWriter out, TaxDocumentResponseBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TaxDocumentResponseBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TaxDocumentResponseBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TaxDocumentResponseBody
  * @throws IOException if the JSON string is invalid with respect to TaxDocumentResponseBody
  */
  public static TaxDocumentResponseBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TaxDocumentResponseBody.class);
  }

 /**
  * Convert an instance of TaxDocumentResponseBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

