/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.mx_platform_api;

import com.mx.client.ApiException;
import com.mx.client.model.InvestmentHoldingResponseBody;
import com.mx.client.model.InvestmentHoldingsDeactivation;
import com.mx.client.model.InvestmentHoldingsResponseBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvestmentHoldingsApi
 */
@Disabled
public class InvestmentHoldingsApiTest {

    private final InvestmentHoldingsApi api = new InvestmentHoldingsApi();

    /**
     * Deactivate user from Investment Holdings
     *
     * This endpoint deactivates the specific user from the &#x60;/investment_holdings&#x60; product. To reactivate a user, use any of the current &#x60;/investment_holding&#x60; endpoints.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deactivateUserTest() throws ApiException {
        String userGuid = null;
        InvestmentHoldingsDeactivation response = api.deactivateUser(userGuid);
        // TODO: test validations
    }

    /**
     * List holdings by user
     *
     * This endpoint lists all holdings associated with the user across all accounts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listHoldingsTest() throws ApiException {
        String userGuid = null;
        Integer page = null;
        Integer recordsPerPage = null;
        InvestmentHoldingsResponseBody response = api.listHoldings(userGuid, page, recordsPerPage);
        // TODO: test validations
    }

    /**
     * List holdings by account
     *
     * This endpoint lists all holdings associated with the particular account defined.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listHoldingsByAccountTest() throws ApiException {
        String accountGuid = null;
        String userGuid = null;
        Integer page = null;
        Integer recordsPerPage = null;
        InvestmentHoldingsResponseBody response = api.listHoldingsByAccount(accountGuid, userGuid, page, recordsPerPage);
        // TODO: test validations
    }

    /**
     * List holdings by member
     *
     * This endpoint lists all holdings associated with the specified member.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listHoldingsByMemberTest() throws ApiException {
        String memberGuid = null;
        String userGuid = null;
        Integer page = null;
        Integer recordsPerPage = null;
        InvestmentHoldingsResponseBody response = api.listHoldingsByMember(memberGuid, userGuid, page, recordsPerPage);
        // TODO: test validations
    }

    /**
     * Read holding
     *
     * Use this endpoint to read the attributes of a specific &#x60;holding&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readHoldingTest() throws ApiException {
        String holdingGuid = null;
        String userGuid = null;
        InvestmentHoldingResponseBody response = api.readHolding(holdingGuid, userGuid);
        // TODO: test validations
    }

}
