/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.mx_platform_api;

import com.mx.client.ApiException;
import com.mx.client.model.MerchantLocationResponseBody;
import com.mx.client.model.MerchantResponseBody;
import com.mx.client.model.MerchantsResponseBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MerchantsApi
 */
@Disabled
public class MerchantsApiTest {

    private final MerchantsApi api = new MerchantsApi();

    /**
     * List merchants
     *
     * This endpoint returns a paginated list of all the merchants in the MX system.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMerchantsTest() throws ApiException {
        String name = null;
        Integer page = null;
        Integer recordsPerPage = null;
        MerchantsResponseBody response = api.listMerchants(name, page, recordsPerPage);
        // TODO: test validations
    }

    /**
     * Read merchant
     *
     * Returns information about a particular merchant, such as a logo, name, and website.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readMerchantTest() throws ApiException {
        String merchantGuid = null;
        MerchantResponseBody response = api.readMerchant(merchantGuid);
        // TODO: test validations
    }

    /**
     * Read merchant location
     *
     * This endpoint returns the specified &#x60;merchant_location&#x60; resource. The &#x60;merchant_location_guid&#x60; can be found on &#x60;transaction&#x60; objects.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readMerchantLocationTest() throws ApiException {
        String merchantLocationGuid = null;
        MerchantLocationResponseBody response = api.readMerchantLocation(merchantLocationGuid);
        // TODO: test validations
    }

}
