/*
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mx.client.mx_platform_api;

import com.mx.client.ApiException;
import com.mx.client.model.TaggingCreateRequestBody;
import com.mx.client.model.TaggingResponseBody;
import com.mx.client.model.TaggingUpdateRequestBody;
import com.mx.client.model.TaggingsResponseBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaggingsApi
 */
@Disabled
public class TaggingsApiTest {

    private final TaggingsApi api = new TaggingsApi();

    /**
     * Create tagging
     *
     * Use this endpoint to create a new association between a tag and a particular transaction, according to their unique GUIDs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTaggingTest() throws ApiException {
        String userGuid = null;
        TaggingCreateRequestBody taggingCreateRequestBody = null;
        TaggingResponseBody response = api.createTagging(userGuid, taggingCreateRequestBody);
        // TODO: test validations
    }

    /**
     * Delete tagging
     *
     * Use this endpoint to delete a tagging according to its unique GUID. If successful, the API will respond with an empty body and a status of 204 NO Content.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTaggingTest() throws ApiException {
        String taggingGuid = null;
        String userGuid = null;
        api.deleteTagging(taggingGuid, userGuid);
        // TODO: test validations
    }

    /**
     * List taggings
     *
     * Use this endpoint to retrieve a list of all the taggings associated with a specific user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTaggingsTest() throws ApiException {
        String userGuid = null;
        Integer page = null;
        Integer recordsPerPage = null;
        TaggingsResponseBody response = api.listTaggings(userGuid, page, recordsPerPage);
        // TODO: test validations
    }

    /**
     * Read tagging
     *
     * Use this endpoint to read the attributes of a &#x60;tagging&#x60; according to its unique GUID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readTaggingTest() throws ApiException {
        String taggingGuid = null;
        String userGuid = null;
        TaggingResponseBody response = api.readTagging(taggingGuid, userGuid);
        // TODO: test validations
    }

    /**
     * Update tagging
     *
     * Use this endpoint to update a tagging.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTaggingTest() throws ApiException {
        String taggingGuid = null;
        String userGuid = null;
        TaggingUpdateRequestBody taggingUpdateRequestBody = null;
        TaggingResponseBody response = api.updateTagging(taggingGuid, userGuid, taggingUpdateRequestBody);
        // TODO: test validations
    }

}
