name: Publish package to the Maven Central Repository

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build settings file
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "ossrh",
                "username": "${env.MAVEN_USERNAME}",
                "password": "${env.MAVEN_PASSWORD}"
              },
              {
                "id": "gpg.passphrase",
                "passphrase": "${env.MAVEN_GPG_PASSPHRASE}"
              }
            ]
          active_profiles: >
            [
              "sign-artifacts"
            ]
          output_file: .m2/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: ossrh
          settings-path: ${{ github.workspace }}
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Maven Central
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
